google_drive:
  folders:
    default: "1ZJl54Kl-kpfPY6WbbSW29YTmDxkejN1F"
    correct_predictions: "1ncxH-PxJW7nJu9Rlwm4LUN3DQg8BGh2f"
    incorrect_predictions: "1oUSNdHGv_jiqSfFi92kniWCnONxlnbR7"
    partially_correct: "1F8x6zMTuReS2_BkUMlJNZcLGbWhyw6Nv" 