[firebase]
type = "service_account"
project_id = "test-bone-b6e69"
private_key_id = "4d8f5c2db2f7470a410c97bc36a391cf2e38c758"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCoGRxooCnKzYzS
x16foxdycGJIoMvPGFeSHw73DitzyAzuq4Ei1LI1unczkrZYw0YCfXjaeR/wg0d8
jObFLe+HCe4s9HWO4il3ePcseW19jKJbDrxQuKbdXFop+4CA+AsZMUt73N7n2dtt
hixzakRLWQKe2Vwz1Ar6yZS7tRqqJkKcw0v893dec4zTO0oX6nIGOQEROR7Op40k
OfsNAsG3qi+yKWDUa9ovu56RujPlkwid9/FQYKKlAMcUWAJZUF5QgRudl5kk3esb
f8LMm2x4BDWJHTkZcEPXY2ieOAB6sKiwguzhwaUesRuLhzth6Y5VklTZ81J8CanB
AGYMGnqVAgMBAAECggEAOOLqmMOe8QlXv1sF/Csiu7EpqZ906Xw44nPNSjFK5i9M
pRZ4KLPnLUSRo2vidq56ykvw8qpr8yZSMmWykQcHGOF071S5VeXWl55hs3TSZ1sI
9JzLgNvEaIQg5TU+GycWBmwGuf+YlcjFt85gy5wqSX9xYhV33PhE0PMX+OAEipDE
Nf36NuD3lrVpUlTG0pOmVIRAR/i8IK90JBSXuh/o5azODjHvXpCF/ZlqRjdtqTor
TyT8w5Kmzqq7upAwZdglciQNgQ+2vmvRoMC77/vMEZ1KN+VoPxd8sZCJyBL/Vzj5
0Y+HGlLQsP8PnFta3hJiuxE4FCIl2wx5wM8RjAm6XwKBgQDhXL2G+k0B9VexV7a3
SOrdN6gJs2TF2d1LiyLjWbPuKD/j/9jLYXPuj4UFb4u1XvrPR8FH9MzRrJarACnS
zw99+D4xlUtEN0yDNXC0uxphkr5zjp3/4KNvdvNjvFh2pl1kFC0tEUpQpu1iIjw6
6CB/uMnhaBvT1FD0KwEkOWWlYwKBgQC+82lROiZKCWzu2S4X/XVFll0nRCWSiDxX
MyXncwrT+wURuSjjPb8JjIRINjqdkW3uWglYjtzWPGaMyjulG6IjPLtmrkqXTv5W
8QyPPYZ3j0frC5oQf8vwAOtBsCHneQ2rtyxsqwozAH2lsQgEVPMdf08tAFENGIBj
kloGXwE9pwKBgQCjeBP6PsFxNDfB6fAdjwTeJir7rmbgpSHCVFCgPUco74U4qzLk
g/IGD5Db2oeqrhScGl53BXk0dk5sB5hO0+dW5qSmbrbD6qDTZAY28qk2Ma14QPEW
1Cl5Bv2RUOOSXSbNG12RnUMcsZjrYA30ZMB+JNo7aLsWsqFuG2uejQvQJQKBgGB5
60Q29RGDIZ6r7DYCwTWfewFT1Qfr/VCxbv05isb/lNgXjSkDEXppnIw/me3yhHBg
3Uf5Jmq3qbiIlQoepBTZonWGqfk42BhlQcs9cqsFoXiILBcZ+pgQXsyZiQfCib2w
lqlw4X5TSShmAX7uzMaihAZgmpLbRkMItqNxbNcRAoGBAN3Pq/wVc1EdFXCTYjni
l01l6KOC5clNay5FRzZCLXtGGdVlZJraX2cd1SArkuYJchY0NhPsErQf2X2DLu9T
guEkmG6YaBuUMwHu+PT0Knh3icZ6st3HkgtaYCyCqdaqdo6yPTNGhCro3PXwr9ll
zq30EI+9G87LEXbJnAzr0jFk
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fdfda@test-bone-b6e69.iam.gserviceaccount.com"
client_id = "113273384621342302025"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fdfda%40test-bone-b6e69.iam.gserviceaccount.com"
universe_domain = "googleapis.com"


[gcp_service_account]
type = "service_account"
project_id = "test-bone-b6e69"
private_key_id = "38d929a99f16cbe529c6c73e4dbe2f60aee8977c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDsExMeGxtAVqIX
6wQlJVkNmlqAnh9UXTeZdJM+uDYZIjLsA+MyZd8DJnJMejwZfcx6KSSAzGQoMZnG
QnvHmzJBBaWv1YbQUsatOUNH3tpf2Jn8rg1Il63TJ+Jb4xuNwmLSvEg2IPc9UD3w
Ms/6KLmoNVmiX2+X6NvPjA7F3TdRKCy/7xgDQFJGGA1aFMFBCau2LRMTyzhSkWOo
NkSXsD9t5+qMO3Rd5zB09FWz8UnpDQrhSF3/FsYDHbHDbPX/0WmGTvR7b+5N5oTP
4nnmBnV7e2GtBBcb6aqDLQoBh5WIhArlTEUxFOA2QXzQRLGnxl8ySxj1DGUE1SC+
35qzAWFbAgMBAAECggEARLyBEoD9/Eu9Qo2RVWd8eHN66nwfzyadK7c/sEFerw7A
GOxA2MnEl1w4Z4Anw5xXTzJviHj6qKFYjtuIwuOzTC9iwMHBUSLo6kMEDgcbOlEM
9P+QqpRPbm3sgKituybgM0/TDr+mfVnBzxBcchAtjoaKJLb4/Rg1+EZlfsMceipT
K7wJouH+/TB5ZBFDzjcjDmb3MkNqNniRw+6G1ODCI/SEAh0Y7SQ7oZA4w6M+H7Dk
k6PtmaUW+U3ibwiUJRT0r1KiVZ4CfJ63mm+KoUW6BrO8MhL9zunSCjr65MyPD+BF
jSyZtwJCeblJBtIsbzwQFJ7n5qSHSuGvY/ORT+rQsQKBgQD/Dr078pRvvq74HVLm
TcqYjqcOOFMog5GIWIPm8q1xbQPkdO3OuEjm+s6mEGrIoqPQzJCse0g2m2Rgr817
/ufEkgSwnlKKtEw6/B/1YUqSeJ3rm2g2GVkkhlGRDFRoqDCsgEeDrBOWsCwvIcw2
gk64sLcIYpg5Or0w+WkTNazQXwKBgQDs8mEXdTbY6EeW4VVSwpaONcwwXJMFZkPs
2jlmGsDdqd38t+b5u996NLxlBaX7SuDWos+Ojx7b19CObZo6hk3xopjb/s+Fv4bA
g7uUr9/S2lNmlutGb0OjXhuqVLNnvSiNoCc/2Qq2Rbetk30iBRMzw+SNbOkhd5mj
Atc9d9rghQKBgQDISMOyemezZBIzhZtefAG2UHbARNyQONikL5XMWg52vjtLP8Kq
DK46qwJxBv1Ddeubf7evqdNoBhgJkKOUVfObuWnzYy+/+ZrOysMxxedwI0UnCU8J
BFiqxMryUrNJx6EJJGaD8DElqEvZ6vlYaHT2tNXVwM52SjjcZ03qpsCAkwKBgBvr
KzmCXCYOqHDEuDL6LpcvC5IfNkuKkzJTPDQlrtfvbfKbEKIYWuqhUBlvIvGLDxb7
NA2OG4q30SEXFPcUYBa6m9xAF9+gg5Ynb3DDkFHd27nYynwQHB4htozJUiJFDYQy
fK1vO23ipRPUrwfVJUASMtnfHVEOMJIegZICj02pAoGBAKZiKB7x4P4FszlxZm/t
3t02V2ifUI76rP5/vUSIrYgL8bqt0nN7LIVheYxmSqwh/EeRl05NH0oCluxkr7WT
4TgYQIwwM/aV1JvJfBlln0i5VDE8AMTwKpDDIBOAZmFtnEKcY9sODshz7BVSCJsn
Fa7bvqIS6j1MAjEx6CQM2ZjC
-----END PRIVATE KEY-----"""
client_email = "bfd-work@test-bone-b6e69.iam.gserviceaccount.com"
client_id = "116129539924657881858"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bfd-work%40test-bone-b6e69.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
